image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./net.akehurst.kotlin.example.addressbook/gradlew build -Pclient=angular
    command: ./net.akehurst.kotlin.example.addressbook/gradlew run -Pclient=angular
