image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./net.akehurst.kotlin.example.addressbook/gradlew build -Pclient=angular
    command: cd net.akehurst.kotlin.example.addressbook/ && ./gradlew run -Pclient=angular
